---
- name: Cambiare la password di un utente su tutti i nodi
  hosts: all
  become: true

  vars:
    nuova_password: "{{ 'Password123!' | password_hash('sha512') }}"

  tasks:
    - name: Aggiornare la password dell'utente developer
      ansible.builtin.user:
        name: developer
        password: "{{ nuova_password }}"