---
# Play 1 - Aggiornamento pacchetti
- name: Aggiornare i pacchetti
  hosts: ubuntu_nodes
  become: true

  tasks:
    - name: Update apt
      ansible.builtin.apt:
        update_cache: yes
        upgrade: yes

# Play 2 - Installare un'applicazione
- name: Installare Apache
  hosts: ubuntu_nodes
  become: true

  tasks:
    - name: Installare Apache2
      ansible.builtin.apt:
        name: apache2
        state: present